### PR TITLE
Maintenance PR

### PR DESCRIPTION
**Pull request by Codex-**
Completed a number of updates and fixes for this PR. This is a maintenance PR only, so no functional changes have been made.

### Changed
- Fixed travis build failing. Then broken it. Then fixed it. Then fixed it again.
  - Updated `NodeJS` to 8 (as LTS has ended for Node 6).
  - Updated `xcode` from 9.2 to 9.4.
  - Updated Android build target from 26 to 28 for NS 5.
  - Updated Android AVD build to use Android API 24 for testing.
- Fixed all linting issues.
- Updated nested `package.json` to reflect the correct repo information and removed the demo/template information.
- Updated paths for use NativeScript 5 pathing (adding `tns-core-modules/`).
- Updated `tns-android` and `tns-ios` from 4.2.0 to 5.3.0.
- Updated pathin in linting commands to be Windows compatible.
- Fixed demo `tsconfig.json` missing app path for compilation.
- Fixed issue where sometimes iOS typings could not resolve the referenced typings.
  - It seems common practice to also include the `/// <reference` in the relevant ts files on top of using `reference.d.ts`. Doing this resolved the build failing for missing iOS typings.
- Fixed spelling and casing issues in `mapbox.android.ts` and mapbox.ios.ts.
  - Fixed some duplicate code.
- Fixed issue where the iOS tests would hang after completion.
  - Required adding `--justlaunch` to the ios test command in `package.json`.
- Fixed `Mapbox.d.ts` issue where autogenerated `readonly` lines were not prefacing any declaration,and thus were casting a `readonly` to the next line. Removed all floating `readonly` declarations.

### Removed
- TravisCI
  - Removed `platform-tools` as was extraneous.
- Demo `package.json`
  - Removed deprecated and extraneous packages.

Sorry for the large PR, took a lot to get the demo and packages up to date!

If accepted, needs a version bump before release etc. I'd advise a major version bump, as updated to NS5.

This is in preparation to investigate updating the Native Mapbox plugins to the latest versions for both iOS and Android.

### CODE REVIEW

**Comment by Codex-** [comment]
image

**Comment by lochstar** [comment]
Looks great. @EddyVerbruggen is a pretty busy guy, I'm sure he'll get to these PR's soon.

**Comment by EddyVerbruggen** [comment]
Sorry man, looks very good. Thanks!!

**Comment by Codex-** [comment]
Thanks Eddy! I'll start looking at upgrading mapbox core next most likely :)

**Pull request merged**
