### PR TITLE
Convert custom url string to NSURL

### PR DESCRIPTION
**Pull request by ahalls**
Resolve issue #69

### CODE REVIEW

**Comment by ahalls** [comment]
@EddyVerbruggen   Found the issue with #69 and completed this PR to illustrate a fix.

**Comment by EddyVerbruggen** [comment]
👍 Awesome, thanks!

**Comment by EddyVerbruggen** [comment]
@ahalls You've been invited to become a collaborator on this project. If you ever need small fixes go ahead and help yourself ;)

**Comment by ahalls** [comment]
@EddyVerbruggen  Thanks for acting on this PR.   I need to bump the version so it's easier to share this fix with my team members.   Can you let me know how to do that or take care of it.  
Thanks -- A

**Comment by EddyVerbruggen** [comment]
Published 2.3.2 🚀

**Pull request merged**
