### PR TITLE
First approach, not complete.

### PR DESCRIPTION
**Pull request by Gcuencam**
It doesn't work correctly, I need your help.

### CODE REVIEW

**Comment by Gcuencam** [comment]
I get the next error:

'Error in mapbox.renderedFeatures: Error: java.lang.Exception: Failed resolving method queryRenderedFeatures on class com.mapbox.mapboxsdk.maps.MapboxMap 

And it's in the API:

https://www.mapbox.com/android-docs/api/map-sdk/5.5.0/com/mapbox/mapboxsdk/maps/MapboxMap.html#queryRenderedFeatures-android.graphics.PointF-java.lang.String...-

**Comment by Gcuencam** [comment]
Hi @EddyVerbruggen, something about this? I have been working about this but I haven't get nothing. Here is an example: https://www.mapbox.com/android-docs/maps/overview/query/

**Comment by EddyVerbruggen** [comment]
Thanks for the effort, I'll take a look and update your fork!

**Comment by EddyVerbruggen** [comment]
Hi! I've updated your fork with something that seems to work a little better. Can you check it out and continue implementation please?

I'm not sure what you'd like to have the method return to the app so I just stringified a few native properties, but that's not the right approach. Ideally we'd like to have a strongly typed object that's sent to the client. Example:

https://github.com/EddyVerbruggen/nativescript-mapbox/blob/3acb086170523e17c6ef0ed94d701fbed45840b2/src/mapbox.common.ts#L384

**Comment by Gcuencam** [comment]
Nice ! I have added two improvements more, first I have added an optional field to QueryRenderedFeaturesOptions, to set only the layers from which you want to obtain information. Second I have added a type Feature, following your recommendation to return a typed object, the field type in Feature is optional because in macOS sdk doesn't exists.

**Comment by EddyVerbruggen** [comment]
Thanks, LGTM!

**Pull request merged**
