### PR TITLE
queryRenderedFeatures - update feature.attributes deserialization

### PR DESCRIPTION
**Pull request by piotrilski**
Hey, thanks for a great plugin @EddyVerbruggen 
The reason of that PR is I wanted to use queryRenderedFeatures({point}) to retrieve ids of my custom-generated polygons (added id property to geoJSON object). In current version, I was getting only null identifiers on iOS. 
For the same use case I found a bug in deserialization of feature's properties NSDictionary (not being able to parse JSON object).

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
Hi!

I'd like to merge this, but I'm not too crazy about the formatting changes of mapbox.d.ts and the bump in the Podfile. Can you perhaps isolate the relevant changes? Otherwise I'll merge and revert those bits.

Cheers,
Eddy

**Comment by piotrilski** [comment]
Done

**Comment by EddyVerbruggen** [comment]
Wonderful, much appreciated!

**Comment by mixaster** [comment]
Will this version be published soon? The bug that's fixed in this PR is sorely needed in the app I'm working on.

**Pull request merged**
