### PR TITLE
LongPress functionality for android and ios

### PR DESCRIPTION
**Pull request by slushnys**
Hello there fellow plugin users.

I present you the LongPress functionality for android and iOS devices.
**Side note** _Remember that iOS devices LongPress functionality is continuous so if you LongPress and drag it will register those events. We could discuss about further implementation/update of it._

Those who are familiar with the plugin already can use it like this  

```typescript
onMapReady(args) {
  let map = args.map;
  map.setOnMapClickListener((point) => console.log('Map tapped: ' + JSON.stringify(point)));
  map.setOnMapLongClickListener((point) => console.log('Map long tapped: ' + JSON.stringify(point)));
}
```

### CODE REVIEW

**Comment by EddyVerbruggen** [comment]
This looks great, thank you!

**Comment by EddyVerbruggen** [comment]
I'll add some documentation and release 4.3.1 later this week.

**Comment by slushnys** [comment]
@EddyVerbruggen I see i haven't been added to the contributions list, I wonder why or how this works?

**Comment by EddyVerbruggen** [comment]
Hi @zslusnys I'm not sure I understand what you mean exactly. Happy to add you anywhere you like though 😀

**Comment by slushnys** [comment]
I haven't been contributing much on github so i'm not sure how this works, but I thought every time someone contributes something in some repo, it should mark them as contributor. That's what i'm trying to find out, I thought I should be marked as a contributor, however I didn't notice github mark me as this however small feature it would be - author. 🤷‍♂️

**Comment by EddyVerbruggen** [comment]
That's not an automatic process. The repo owner can decide to add anyone to the list of contributors ('collaborators' actually) so they can fi. push to the repo directly instead of making PRs via a fork. I'd be happy to add you though (and just did so).

**Comment by EddyVerbruggen** [comment]
I can also add you to the `package.json` as a contributor, but that's a manual process as well and (now) you can even do it yourself.

**Comment by slushnys** [comment]
> That's not an automatic process. The repo owner can decide to add anyone to the list of contributors ('collaborators' actually) so they can fi. push to the repo directly instead of making PRs via a fork. I'd be happy to add you though (and just did so).

Thank you for that, I'll see if I face any new things that bug me along the way and update the repo with new features then.

**Pull request merged**
